<?php
$_cms_tree_node_table='shop_tree_nodes';
$_cms_tree_node_details='shop_tree_node_details';
$_cms_shop_orders='shop_orders';
$_cms_shop_orders_goods='shop_orders_goods';
$_cms_directories='shop_directories';
$_cms_directories_data='shop_directories_data';

$_cms_goods_list_page_length=20;
$_cms_goods_images_url="$_base_site_root_url/data/goods_images";
$_cms_goods_images_path="$_base_site_root_path/data/goods_images";
$_cms_goods_images_jpeg_quality=85;
$_cms_goods_images_thumbnail_size=190;
$_cms_goods_images_size_x=400;
$_cms_goods_images_size_y=400;

$_admin_good_title_suffix='collection|article';

// ID меню магазина (пунктами меню являются категории товаров)
$_shop_menu_id=2;

// Параметры товаров
// id		- уникальный id параметра
// name		- название параметра
// type		- тип данных параметра (e(enum)|d(digital)|i(image)|c(char))
// options	- варианты выбора для типа enum (разделитель '|')
// need		- если true то это обязательный для ввода параметр
// limit	- количество данных для признака (например количество изображений для типа 'image')
$_cms_good_types=array(
	array('id'=>'1', 'name'=>'Люстры потолочные', 'details'=>array(
		array('id'=>'maker', 'name'=>'Производитель', 'type'=>'do',  'options'=>'1', 'filter'=>true, 'need'=>true),
		array('id'=>'country', 'name'=>'Страна', 'type'=>'do', 'options'=>'2', 'filter'=>true),
		array('id'=>'type', 'name'=>'Категория', 'type'=>'do', 'options'=>'8', 'filter'=>true),
		array('id'=>'height', 'name'=>'Высота (мм)', 'type'=>'d'),
		array('id'=>'width', 'name'=>'Ширина (мм)', 'type'=>'d'),
		array('id'=>'length', 'name'=>'Длинна (мм)', 'type'=>'d'),
		array('id'=>'diametr', 'name'=>'Диаметр (мм)', 'type'=>'d'),
		array('id'=>'lamp_type', 'name'=>'Тип лампочки (основной)', 'type'=>'e',  'options'=>'E14|E27|G9|G4|R7S|GU10|GX5.3|GY6.35', 'need'=>true),
		array('id'=>'power', 'name'=>'Мощность лампы(Вт)', 'type'=>'d', 'need'=>true),
		array('id'=>'lamp_count', 'name'=>'Количество ламп', 'type'=>'d', 'need'=>true),
		array('id'=>'area', 'name'=>'Площадь освещения м2', 'type'=>'d'),
		array('id'=>'collection', 'name'=>'Коллекция', 'type'=>'s', 'filter'=>true),
		array('id'=>'style', 'name'=>'Стиль светильника', 'type'=>'do',  'options'=>'3'),
		array('id'=>'placing', 'name'=>'Способ размещения', 'type'=>'do',  'options'=>'4'),
		array('id'=>'material', 'name'=>'Материал', 'type'=>'dm',  'options'=>'5'),
		array('id'=>'color', 'name'=>'Цвет', 'type'=>'dm',  'options'=>'6'),
		array('id'=>'color_glass', 'name'=>'Цвет стекла', 'type'=>'dm',  'options'=>'7'),
		array('id'=>'lamps_exists', 'name'=>'Лампочки в комплекте', 'type'=>'c'),
		array('id'=>'price', 'name'=>'"Цена"', 'type'=>'d'),
	)),

	array('id'=>'2', 'name'=>'Люстры подвесные', 'details'=>array(
		array('id'=>'maker', 'name'=>'Производитель', 'type'=>'do',  'options'=>'1', 'filter'=>true, 'need'=>true),
		array('id'=>'country', 'name'=>'Страна', 'type'=>'do', 'options'=>'2', 'filter'=>true),
		array('id'=>'type', 'name'=>'Категория', 'type'=>'do', 'options'=>'9', 'filter'=>true),
		array('id'=>'height', 'name'=>'Высота (мм)', 'type'=>'d'),
		array('id'=>'width', 'name'=>'Ширина (мм)', 'type'=>'d'),
		array('id'=>'length', 'name'=>'Длинна (мм)', 'type'=>'d'),
		array('id'=>'diametr', 'name'=>'Диаметр (мм)', 'type'=>'d'),
		array('id'=>'lamp_type', 'name'=>'Тип лампочки (основной)', 'type'=>'e',  'options'=>'E14|E27|G9|G4|R7S|GU10|GX5.3|GY6.35', 'need'=>true),
		array('id'=>'power', 'name'=>'Мощность лампы(Вт)', 'type'=>'d', 'need'=>true),
		array('id'=>'lamp_count', 'name'=>'Количество ламп', 'type'=>'d', 'need'=>true),
		array('id'=>'area', 'name'=>'Площадь освещения м2', 'type'=>'d'),
		array('id'=>'collection', 'name'=>'Коллекция', 'type'=>'s', 'filter'=>true),
		array('id'=>'style', 'name'=>'Стиль светильника', 'type'=>'do',  'options'=>'3'),
		array('id'=>'placing', 'name'=>'Способ размещения', 'type'=>'do',  'options'=>'4'),
		array('id'=>'material', 'name'=>'Материал', 'type'=>'dm',  'options'=>'5'),
		array('id'=>'color', 'name'=>'Цвет', 'type'=>'dm',  'options'=>'6'),
		array('id'=>'color_glass', 'name'=>'Цвет стекла', 'type'=>'dm',  'options'=>'7'),
		array('id'=>'lamps_exists', 'name'=>'Лампочки в комплекте', 'type'=>'c'),
		array('id'=>'price', 'name'=>'"Цена"', 'type'=>'d'),
	)),

	array('id'=>'3', 'name'=>'Бра', 'details'=>array(
		array('id'=>'maker', 'name'=>'Производитель', 'type'=>'do',  'options'=>'1', 'filter'=>true, 'need'=>true),
		array('id'=>'country', 'name'=>'Страна', 'type'=>'do', 'options'=>'2', 'filter'=>true),
		array('id'=>'type', 'name'=>'Категория', 'type'=>'do', 'options'=>'10', 'filter'=>true),
		array('id'=>'height', 'name'=>'Высота (мм)', 'type'=>'d'),
		array('id'=>'width', 'name'=>'Ширина (мм)', 'type'=>'d'),
		array('id'=>'length', 'name'=>'Длинна (мм)', 'type'=>'d'),
		array('id'=>'diametr', 'name'=>'Диаметр (мм)', 'type'=>'d'),
		array('id'=>'offset', 'name'=>'Вылет (мм)', 'type'=>'d'),
		array('id'=>'lamp_type', 'name'=>'Тип лампочки (основной)', 'type'=>'e',  'options'=>'E14|E27|G9|G4|R7S|GU10|GX5.3|GY6.35', 'need'=>true),
		array('id'=>'power', 'name'=>'Мощность лампы(Вт)', 'type'=>'d', 'need'=>true),
		array('id'=>'lamp_count', 'name'=>'Количество ламп', 'type'=>'d', 'need'=>true),
		array('id'=>'area', 'name'=>'Площадь освещения м2', 'type'=>'d'),
		array('id'=>'collection', 'name'=>'Коллекция', 'type'=>'s', 'filter'=>true),
		array('id'=>'style', 'name'=>'Стиль светильника', 'type'=>'do',  'options'=>'3'),
		array('id'=>'placing', 'name'=>'Способ размещения', 'type'=>'do',  'options'=>'4'),
		array('id'=>'material', 'name'=>'Материал', 'type'=>'dm',  'options'=>'5'),
		array('id'=>'color', 'name'=>'Цвет', 'type'=>'dm',  'options'=>'6'),
		array('id'=>'color_glass', 'name'=>'Цвет стекла', 'type'=>'dm',  'options'=>'7'),
		array('id'=>'lamps_exists', 'name'=>'Лампочки в комплекте', 'type'=>'c'),
		array('id'=>'price', 'name'=>'"Цена"', 'type'=>'d'),
	)),

	array('id'=>'4', 'name'=>'Детские светильники', 'details'=>array(
		array('id'=>'maker', 'name'=>'Производитель', 'type'=>'do',  'options'=>'1', 'filter'=>true, 'need'=>true),
		array('id'=>'country', 'name'=>'Страна', 'type'=>'do', 'options'=>'2', 'filter'=>true),
		array('id'=>'height', 'name'=>'Высота (мм)', 'type'=>'d'),
		array('id'=>'width', 'name'=>'Ширина (мм)', 'type'=>'d'),
		array('id'=>'length', 'name'=>'Длинна (мм)', 'type'=>'d'),
		array('id'=>'diametr', 'name'=>'Диаметр (мм)', 'type'=>'d'),
		array('id'=>'lamp_type', 'name'=>'Тип лампочки (основной)', 'type'=>'e',  'options'=>'E14|E27|G9|G4|R7S|GU10|GX5.3|GY6.35', 'need'=>true),
		array('id'=>'power', 'name'=>'Мощность лампы(Вт)', 'type'=>'d', 'need'=>true),
		array('id'=>'lamp_count', 'name'=>'Количество ламп', 'type'=>'d', 'need'=>true),
		array('id'=>'area', 'name'=>'Площадь освещения м2', 'type'=>'d'),
		array('id'=>'collection', 'name'=>'Коллекция', 'type'=>'s', 'filter'=>true),
		array('id'=>'style', 'name'=>'Стиль светильника', 'type'=>'do',  'options'=>'3'),
		array('id'=>'placing', 'name'=>'Способ размещения', 'type'=>'do',  'options'=>'4'),
		array('id'=>'material', 'name'=>'Материал', 'type'=>'dm',  'options'=>'5'),
		array('id'=>'color', 'name'=>'Цвет', 'type'=>'dm',  'options'=>'6'),
		array('id'=>'color_glass', 'name'=>'Цвет стекла', 'type'=>'dm',  'options'=>'7'),
		array('id'=>'lamps_exists', 'name'=>'Лампочки в комплекте', 'type'=>'c'),
		array('id'=>'price', 'name'=>'"Цена"', 'type'=>'d'),
	)),

	array('id'=>'5', 'name'=>'Светильники для кухни', 'details'=>array(
		array('id'=>'maker', 'name'=>'Производитель', 'type'=>'do',  'options'=>'1', 'filter'=>true, 'need'=>true),
		array('id'=>'country', 'name'=>'Страна', 'type'=>'do', 'options'=>'2', 'filter'=>true),
		array('id'=>'type', 'name'=>'Категория', 'type'=>'do', 'options'=>'11', 'filter'=>true),
		array('id'=>'height', 'name'=>'Высота (мм)', 'type'=>'d'),
		array('id'=>'width', 'name'=>'Ширина (мм)', 'type'=>'d'),
		array('id'=>'length', 'name'=>'Длинна (мм)', 'type'=>'d'),
		array('id'=>'diametr', 'name'=>'Диаметр (мм)', 'type'=>'d'),
		array('id'=>'lamp_type', 'name'=>'Тип лампочки (основной)', 'type'=>'e',  'options'=>'E14|E27|G9|G4|R7S|GU10|GX5.3|GY6.35', 'need'=>true),
		array('id'=>'power', 'name'=>'Мощность лампы(Вт)', 'type'=>'d', 'need'=>true),
		array('id'=>'lamp_count', 'name'=>'Количество ламп', 'type'=>'d', 'need'=>true),
		array('id'=>'area', 'name'=>'Площадь освещения м2', 'type'=>'d'),
		array('id'=>'collection', 'name'=>'Коллекция', 'type'=>'s', 'filter'=>true),
		array('id'=>'style', 'name'=>'Стиль светильника', 'type'=>'do',  'options'=>'3'),
		array('id'=>'placing', 'name'=>'Способ размещения', 'type'=>'do',  'options'=>'4'),
		array('id'=>'material', 'name'=>'Материал', 'type'=>'dm',  'options'=>'5'),
		array('id'=>'color', 'name'=>'Цвет', 'type'=>'dm',  'options'=>'6'),
		array('id'=>'color_glass', 'name'=>'Цвет стекла', 'type'=>'dm',  'options'=>'7'),
		array('id'=>'lamps_exists', 'name'=>'Лампочки в комплекте', 'type'=>'c'),
		array('id'=>'price', 'name'=>'"Цена"', 'type'=>'d'),
	)),

	array('id'=>'6', 'name'=>'Настенно потолочные светильники', 'details'=>array(
		array('id'=>'maker', 'name'=>'Производитель', 'type'=>'do',  'options'=>'1', 'filter'=>true, 'need'=>true),
		array('id'=>'country', 'name'=>'Страна', 'type'=>'do', 'options'=>'2', 'filter'=>true),
		array('id'=>'type', 'name'=>'Категория', 'type'=>'do', 'options'=>'12', 'filter'=>true),
		array('id'=>'height', 'name'=>'Высота (мм)', 'type'=>'d'),
		array('id'=>'width', 'name'=>'Ширина (мм)', 'type'=>'d'),
		array('id'=>'length', 'name'=>'Длинна (мм)', 'type'=>'d'),
		array('id'=>'diametr', 'name'=>'Диаметр (мм)', 'type'=>'d'),
		array('id'=>'offset', 'name'=>'Вылет (мм)', 'type'=>'d'),
		array('id'=>'lamp_type', 'name'=>'Тип лампочки (основной)', 'type'=>'e',  'options'=>'E14|E27|G9|G4|R7S|GU10|GX5.3|GY6.35', 'need'=>true),
		array('id'=>'power', 'name'=>'Мощность лампы(Вт)', 'type'=>'d', 'need'=>true),
		array('id'=>'lamp_count', 'name'=>'Количество ламп', 'type'=>'d', 'need'=>true),
		array('id'=>'area', 'name'=>'Площадь освещения м2', 'type'=>'d'),
		array('id'=>'collection', 'name'=>'Коллекция', 'type'=>'s', 'filter'=>true),
		array('id'=>'style', 'name'=>'Стиль светильника', 'type'=>'do',  'options'=>'3'),
		array('id'=>'placing', 'name'=>'Способ размещения', 'type'=>'do',  'options'=>'4'),
		array('id'=>'material', 'name'=>'Материал', 'type'=>'dm',  'options'=>'5'),
		array('id'=>'color', 'name'=>'Цвет', 'type'=>'dm',  'options'=>'6'),
		array('id'=>'color_glass', 'name'=>'Цвет стекла', 'type'=>'dm',  'options'=>'7'),
		array('id'=>'lamps_exists', 'name'=>'Лампочки в комплекте', 'type'=>'c'),
		array('id'=>'price', 'name'=>'"Цена"', 'type'=>'d'),
	)),

	array('id'=>'7', 'name'=>'Встраиваемый светильник', 'details'=>array(
		array('id'=>'maker', 'name'=>'Производитель', 'type'=>'do',  'options'=>'1', 'filter'=>true, 'need'=>true),
		array('id'=>'country', 'name'=>'Страна', 'type'=>'do', 'options'=>'2', 'filter'=>true),
		array('id'=>'type', 'name'=>'Категория', 'type'=>'do', 'options'=>'13', 'filter'=>true),
		array('id'=>'diametr', 'name'=>'Диаметр (мм)', 'type'=>'d'),
		array('id'=>'built-in_height', 'name'=>'Высота встраиваемой части (мм)', 'type'=>'d'),
		array('id'=>'built-in_diametr', 'name'=>'Диаметр врезного отверстия (мм)', 'type'=>'d'),
		array('id'=>'width', 'name'=>'Ширина (мм)', 'type'=>'d'),
		array('id'=>'length', 'name'=>'Длинна (мм)', 'type'=>'d'),
		array('id'=>'voltage', 'name'=>'Напряжение (В)', 'type'=>'s'),
		array('id'=>'lamp_type', 'name'=>'Тип лампочки (основной)', 'type'=>'e',  'options'=>'E14|E27|G9|G4|R7S|GU10|GX5.3|GY6.35', 'need'=>true),
		array('id'=>'power', 'name'=>'Мощность лампы(Вт)', 'type'=>'d', 'need'=>true),
		array('id'=>'lamp_count', 'name'=>'Количество ламп', 'type'=>'d', 'need'=>true),
		array('id'=>'collection', 'name'=>'Коллекция', 'type'=>'s', 'filter'=>true),
		array('id'=>'style', 'name'=>'Стиль светильника', 'type'=>'do',  'options'=>'3'),
		array('id'=>'placing', 'name'=>'Способ размещения', 'type'=>'do',  'options'=>'4'),
		array('id'=>'material', 'name'=>'Материал', 'type'=>'dm',  'options'=>'5'),
		array('id'=>'color', 'name'=>'Цвет', 'type'=>'dm',  'options'=>'6'),
		array('id'=>'color_glass', 'name'=>'Цвет стекла', 'type'=>'dm',  'options'=>'7'),
		array('id'=>'lamps_exists', 'name'=>'Лампочки в комплекте', 'type'=>'c'),
		array('id'=>'price', 'name'=>'"Цена"', 'type'=>'d'),
	)),

	array('id'=>'8', 'name'=>'Светильники для ванной', 'details'=>array(
		array('id'=>'maker', 'name'=>'Производитель', 'type'=>'do',  'options'=>'1', 'filter'=>true, 'need'=>true),
		array('id'=>'country', 'name'=>'Страна', 'type'=>'do', 'options'=>'2', 'filter'=>true),
		array('id'=>'type', 'name'=>'Категория', 'type'=>'do', 'options'=>'14', 'filter'=>true),
		array('id'=>'height', 'name'=>'Высота (мм)', 'type'=>'d'),
		array('id'=>'width', 'name'=>'Ширина (мм)', 'type'=>'d'),
		array('id'=>'length', 'name'=>'Длинна (мм)', 'type'=>'d'),
		array('id'=>'diametr', 'name'=>'Диаметр (мм)', 'type'=>'d'),
		array('id'=>'voltage', 'name'=>'Напряжение (В)', 'type'=>'s'),
		array('id'=>'lamp_type', 'name'=>'Тип лампочки (основной)', 'type'=>'e',  'options'=>'E14|E27|G9|G4|R7S|GU10|GX5.3|GY6.35', 'need'=>true),
		array('id'=>'power', 'name'=>'Мощность лампы(Вт)', 'type'=>'d', 'need'=>true),
		array('id'=>'lamp_count', 'name'=>'Количество ламп', 'type'=>'d', 'need'=>true),
		array('id'=>'area', 'name'=>'Площадь освещения м2', 'type'=>'d'),
		array('id'=>'collection', 'name'=>'Коллекция', 'type'=>'s', 'filter'=>true),
		array('id'=>'style', 'name'=>'Стиль светильника', 'type'=>'do',  'options'=>'3'),
		array('id'=>'placing', 'name'=>'Способ размещения', 'type'=>'do',  'options'=>'4'),
		array('id'=>'material', 'name'=>'Материал', 'type'=>'dm',  'options'=>'5'),
		array('id'=>'color', 'name'=>'Цвет', 'type'=>'dm',  'options'=>'6'),
		array('id'=>'color_glass', 'name'=>'Цвет стекла', 'type'=>'dm',  'options'=>'7'),
		array('id'=>'lamps_exists', 'name'=>'Лампочки в комплекте', 'type'=>'c'),
		array('id'=>'price', 'name'=>'"Цена"', 'type'=>'d'),
	)),

	array('id'=>'9', 'name'=>'Подсветка для картин и зеркал', 'details'=>array(
		array('id'=>'maker', 'name'=>'Производитель', 'type'=>'do',  'options'=>'1', 'filter'=>true, 'need'=>true),
		array('id'=>'country', 'name'=>'Страна', 'type'=>'do', 'options'=>'2', 'filter'=>true),
		array('id'=>'height', 'name'=>'Высота (мм)', 'type'=>'d'),
		array('id'=>'width', 'name'=>'Ширина (мм)', 'type'=>'d'),
		array('id'=>'length', 'name'=>'Длинна (мм)', 'type'=>'d'),
		array('id'=>'offset', 'name'=>'Вылет (мм)', 'type'=>'d'),
		array('id'=>'voltage', 'name'=>'Напряжение (В)', 'type'=>'s'),
		array('id'=>'lamp_type', 'name'=>'Тип лампочки (основной)', 'type'=>'e',  'options'=>'E14|E27|G9|G4|R7S|GU10|GX5.3|GY6.35|LED', 'need'=>true),
		array('id'=>'power', 'name'=>'Мощность лампы(Вт)', 'type'=>'d', 'need'=>true),
		array('id'=>'lamp_count', 'name'=>'Количество ламп', 'type'=>'d', 'need'=>true),
		array('id'=>'area', 'name'=>'Площадь освещения м2', 'type'=>'d'),
		array('id'=>'collection', 'name'=>'Коллекция', 'type'=>'s', 'filter'=>true),
		array('id'=>'style', 'name'=>'Стиль светильника', 'type'=>'do',  'options'=>'3'),
		array('id'=>'placing', 'name'=>'Способ размещения', 'type'=>'do',  'options'=>'4'),
		array('id'=>'material', 'name'=>'Материал', 'type'=>'dm',  'options'=>'5'),
		array('id'=>'color', 'name'=>'Цвет', 'type'=>'dm',  'options'=>'6'),
		array('id'=>'color_glass', 'name'=>'Цвет стекла', 'type'=>'dm',  'options'=>'7'),
		array('id'=>'lamps_exists', 'name'=>'Лампочки в комплекте', 'type'=>'c'),
		array('id'=>'price', 'name'=>'"Цена"', 'type'=>'d'),
	)),

	array('id'=>'10', 'name'=>'Подвесные светильники', 'details'=>array(
		array('id'=>'maker', 'name'=>'Производитель', 'type'=>'do',  'options'=>'1', 'filter'=>true, 'need'=>true),
		array('id'=>'country', 'name'=>'Страна', 'type'=>'do', 'options'=>'2', 'filter'=>true),
		array('id'=>'type', 'name'=>'Категория', 'type'=>'do', 'options'=>'15', 'filter'=>true),
		array('id'=>'height', 'name'=>'Высота (мм)', 'type'=>'d'),
		array('id'=>'width', 'name'=>'Ширина (мм)', 'type'=>'d'),
		array('id'=>'length', 'name'=>'Длинна (мм)', 'type'=>'d'),
		array('id'=>'diametr', 'name'=>'Диаметр (мм)', 'type'=>'d'),
		array('id'=>'voltage', 'name'=>'Напряжение (В)', 'type'=>'s'),
		array('id'=>'lamp_type', 'name'=>'Тип лампочки (основной)', 'type'=>'e',  'options'=>'E14|E27|G9|G4|R7S|GU10|GX5.3|GY6.35', 'need'=>true),
		array('id'=>'power', 'name'=>'Мощность лампы(Вт)', 'type'=>'d', 'need'=>true),
		array('id'=>'lamp_count', 'name'=>'Количество ламп', 'type'=>'d', 'need'=>true),
		array('id'=>'area', 'name'=>'Площадь освещения м2', 'type'=>'d'),
		array('id'=>'collection', 'name'=>'Коллекция', 'type'=>'s', 'filter'=>true),
		array('id'=>'style', 'name'=>'Стиль светильника', 'type'=>'do',  'options'=>'3'),
		array('id'=>'placing', 'name'=>'Способ размещения', 'type'=>'do',  'options'=>'4'),
		array('id'=>'material', 'name'=>'Материал', 'type'=>'dm',  'options'=>'5'),
		array('id'=>'color', 'name'=>'Цвет', 'type'=>'dm',  'options'=>'6'),
		array('id'=>'color_glass', 'name'=>'Цвет стекла', 'type'=>'dm',  'options'=>'7'),
		array('id'=>'lamps_exists', 'name'=>'Лампочки в комплекте', 'type'=>'c'),
		array('id'=>'price', 'name'=>'"Цена"', 'type'=>'d'),
	)),

	array('id'=>'11', 'name'=>'Торшеры', 'details'=>array(
		array('id'=>'maker', 'name'=>'Производитель', 'type'=>'do',  'options'=>'1', 'filter'=>true, 'need'=>true),
		array('id'=>'country', 'name'=>'Страна', 'type'=>'do', 'options'=>'2', 'filter'=>true),
		array('id'=>'type', 'name'=>'Категория', 'type'=>'do', 'options'=>'16', 'filter'=>true),
		array('id'=>'height', 'name'=>'Высота (мм)', 'type'=>'d'),
		array('id'=>'width', 'name'=>'Ширина (мм)', 'type'=>'d'),
		array('id'=>'length', 'name'=>'Длинна (мм)', 'type'=>'d'),
		array('id'=>'diametr', 'name'=>'Диаметр (мм)', 'type'=>'d'),
		array('id'=>'voltage', 'name'=>'Напряжение (В)', 'type'=>'s'),
		array('id'=>'lamp_type', 'name'=>'Тип лампочки (основной)', 'type'=>'e',  'options'=>'E14|E27|G9|G4|R7S|GU10|GX5.3|GY6.35', 'need'=>true),
		array('id'=>'power', 'name'=>'Мощность лампы(Вт)', 'type'=>'d', 'need'=>true),
		array('id'=>'lamp_count', 'name'=>'Количество ламп', 'type'=>'d', 'need'=>true),
		array('id'=>'area', 'name'=>'Площадь освещения м2', 'type'=>'d'),
		array('id'=>'collection', 'name'=>'Коллекция', 'type'=>'s', 'filter'=>true),
		array('id'=>'style', 'name'=>'Стиль светильника', 'type'=>'do',  'options'=>'3'),
		array('id'=>'material', 'name'=>'Материал', 'type'=>'dm',  'options'=>'5'),
		array('id'=>'color', 'name'=>'Цвет', 'type'=>'dm',  'options'=>'6'),
		array('id'=>'color_glass', 'name'=>'Цвет стекла', 'type'=>'dm',  'options'=>'7'),
		array('id'=>'lamps_exists', 'name'=>'Лампочки в комплекте', 'type'=>'c'),
		array('id'=>'price', 'name'=>'"Цена"', 'type'=>'d'),
	)),

	array('id'=>'12', 'name'=>'Настольные лампы', 'details'=>array(
		array('id'=>'maker', 'name'=>'Производитель', 'type'=>'do',  'options'=>'1', 'filter'=>true, 'need'=>true),
		array('id'=>'country', 'name'=>'Страна', 'type'=>'do', 'options'=>'2', 'filter'=>true),
		array('id'=>'type', 'name'=>'Категория', 'type'=>'do', 'options'=>'17', 'filter'=>true),
		array('id'=>'height', 'name'=>'Высота (мм)', 'type'=>'d'),
		array('id'=>'width', 'name'=>'Ширина (мм)', 'type'=>'d'),
		array('id'=>'length', 'name'=>'Длинна (мм)', 'type'=>'d'),
		array('id'=>'diametr', 'name'=>'Диаметр (мм)', 'type'=>'d'),
		array('id'=>'voltage', 'name'=>'Напряжение (В)', 'type'=>'s'),
		array('id'=>'lamp_type', 'name'=>'Тип лампочки (основной)', 'type'=>'e',  'options'=>'E14|E27|G9|G4|R7S|GU10|GX5.3|GY6.35', 'need'=>true),
		array('id'=>'power', 'name'=>'Мощность лампы(Вт)', 'type'=>'d', 'need'=>true),
		array('id'=>'lamp_count', 'name'=>'Количество ламп', 'type'=>'d', 'need'=>true),
		array('id'=>'area', 'name'=>'Площадь освещения м2', 'type'=>'d'),
		array('id'=>'collection', 'name'=>'Коллекция', 'type'=>'s', 'filter'=>true),
		array('id'=>'style', 'name'=>'Стиль светильника', 'type'=>'do',  'options'=>'3'),
		array('id'=>'material', 'name'=>'Материал', 'type'=>'dm',  'options'=>'5'),
		array('id'=>'color', 'name'=>'Цвет', 'type'=>'dm',  'options'=>'6'),
		array('id'=>'color_glass', 'name'=>'Цвет стекла', 'type'=>'dm',  'options'=>'7'),
		array('id'=>'lamps_exists', 'name'=>'Лампочки в комплекте', 'type'=>'c'),
		array('id'=>'price', 'name'=>'"Цена"', 'type'=>'d'),
	)),

	array('id'=>'13', 'name'=>'Хрустальные люстры', 'details'=>array(
		array('id'=>'maker', 'name'=>'Производитель', 'type'=>'do',  'options'=>'1', 'filter'=>true, 'need'=>true),
		array('id'=>'country', 'name'=>'Страна', 'type'=>'do', 'options'=>'2', 'filter'=>true),
		array('id'=>'height', 'name'=>'Высота (мм)', 'type'=>'d'),
		array('id'=>'width', 'name'=>'Ширина (мм)', 'type'=>'d'),
		array('id'=>'length', 'name'=>'Длинна (мм)', 'type'=>'d'),
		array('id'=>'diametr', 'name'=>'Диаметр (мм)', 'type'=>'d'),
		array('id'=>'lamp_type', 'name'=>'Тип лампочки (основной)', 'type'=>'e',  'options'=>'E14|E27|G9|G4|R7S|GU10|GX5.3|GY6.35', 'need'=>true),
		array('id'=>'power', 'name'=>'Мощность лампы(Вт)', 'type'=>'d', 'need'=>true),
		array('id'=>'lamp_count', 'name'=>'Количество ламп', 'type'=>'d', 'need'=>true),
		array('id'=>'area', 'name'=>'Площадь освещения м2', 'type'=>'d'),
		array('id'=>'collection', 'name'=>'Коллекция', 'type'=>'s', 'filter'=>true),
		array('id'=>'style', 'name'=>'Стиль светильника', 'type'=>'do',  'options'=>'3'),
		array('id'=>'placing', 'name'=>'Способ размещения', 'type'=>'do',  'options'=>'4'),
		array('id'=>'material', 'name'=>'Материал', 'type'=>'dm',  'options'=>'5'),
		array('id'=>'color', 'name'=>'Цвет', 'type'=>'dm',  'options'=>'6'),
		array('id'=>'color_glass', 'name'=>'Цвет стекла', 'type'=>'dm',  'options'=>'7'),
		array('id'=>'lamps_exists', 'name'=>'Лампочки в комплекте', 'type'=>'c'),
		array('id'=>'price', 'name'=>'"Цена"', 'type'=>'d'),
	)),

	array('id'=>'14', 'name'=>'Светильники уличные', 'details'=>array(
		array('id'=>'maker', 'name'=>'Производитель', 'type'=>'do',  'options'=>'1', 'filter'=>true, 'need'=>true),
		array('id'=>'country', 'name'=>'Страна', 'type'=>'do', 'options'=>'2', 'filter'=>true),
		array('id'=>'type', 'name'=>'Категория', 'type'=>'do', 'options'=>'18', 'filter'=>true),
		array('id'=>'height', 'name'=>'Высота (мм)', 'type'=>'d'),
		array('id'=>'width', 'name'=>'Ширина (мм)', 'type'=>'d'),
		array('id'=>'length', 'name'=>'Длинна (мм)', 'type'=>'d'),
		array('id'=>'diametr', 'name'=>'Диаметр (мм)', 'type'=>'d'),
		array('id'=>'offset', 'name'=>'Вылет (мм)', 'type'=>'d'),
		array('id'=>'lamp_type', 'name'=>'Тип лампочки (основной)', 'type'=>'e',  'options'=>'E14|E27|G9|G4|R7S|GU10|GX5.3|GY6.35', 'need'=>true),
		array('id'=>'power', 'name'=>'Мощность лампы(Вт)', 'type'=>'d', 'need'=>true),
		array('id'=>'lamp_count', 'name'=>'Количество ламп', 'type'=>'d', 'need'=>true),
		array('id'=>'area', 'name'=>'Площадь освещения м2', 'type'=>'d'),
		array('id'=>'collection', 'name'=>'Коллекция', 'type'=>'s', 'filter'=>true),
		array('id'=>'style', 'name'=>'Стиль светильника', 'type'=>'do',  'options'=>'3'),
		array('id'=>'placing', 'name'=>'Способ размещения', 'type'=>'do',  'options'=>'4'),
		array('id'=>'material', 'name'=>'Материал', 'type'=>'dm',  'options'=>'5'),
		array('id'=>'color', 'name'=>'Цвет', 'type'=>'dm',  'options'=>'6'),
		array('id'=>'color_glass', 'name'=>'Цвет стекла', 'type'=>'dm',  'options'=>'7'),
		array('id'=>'lamps_exists', 'name'=>'Лампочки в комплекте', 'type'=>'c'),
		array('id'=>'price', 'name'=>'"Цена"', 'type'=>'d'),
	)),

	array('id'=>'15', 'name'=>'Споты и трек-системы', 'details'=>array(
		array('id'=>'maker', 'name'=>'Производитель', 'type'=>'do',  'options'=>'1', 'filter'=>true, 'need'=>true),
		array('id'=>'country', 'name'=>'Страна', 'type'=>'do', 'options'=>'2', 'filter'=>true),
		array('id'=>'type', 'name'=>'Категория', 'type'=>'do', 'options'=>'18', 'filter'=>true),
		array('id'=>'height', 'name'=>'Высота (мм)', 'type'=>'d'),
		array('id'=>'width', 'name'=>'Ширина (мм)', 'type'=>'d'),
		array('id'=>'length', 'name'=>'Длинна (мм)', 'type'=>'d'),
		array('id'=>'diametr', 'name'=>'Диаметр (мм)', 'type'=>'d'),
		array('id'=>'offset', 'name'=>'Вылет (мм)', 'type'=>'d'),
		array('id'=>'lamp_type', 'name'=>'Тип лампочки (основной)', 'type'=>'e',  'options'=>'E14|E27|G9|G4|R7S|GU10|GX5.3|GY6.35', 'need'=>true),
		array('id'=>'power', 'name'=>'Мощность лампы(Вт)', 'type'=>'d', 'need'=>true),
		array('id'=>'lamp_count', 'name'=>'Количество ламп', 'type'=>'d', 'need'=>true),
		array('id'=>'area', 'name'=>'Площадь освещения м2', 'type'=>'d'),
		array('id'=>'collection', 'name'=>'Коллекция', 'type'=>'s', 'filter'=>true),
		array('id'=>'style', 'name'=>'Стиль светильника', 'type'=>'do',  'options'=>'3'),
		array('id'=>'placing', 'name'=>'Способ размещения', 'type'=>'do',  'options'=>'4'),
		array('id'=>'material', 'name'=>'Материал', 'type'=>'dm',  'options'=>'5'),
		array('id'=>'color', 'name'=>'Цвет', 'type'=>'dm',  'options'=>'6'),
		array('id'=>'color_glass', 'name'=>'Цвет стекла', 'type'=>'dm',  'options'=>'7'),
		array('id'=>'lamps_exists', 'name'=>'Лампочки в комплекте', 'type'=>'c'),
		array('id'=>'price', 'name'=>'"Цена"', 'type'=>'d'),
	)),

	array('id'=>'16', 'name'=>'Споты и трек-системы', 'details'=>array(
		array('id'=>'maker', 'name'=>'Производитель', 'type'=>'do',  'options'=>'1', 'filter'=>true, 'need'=>true),
		array('id'=>'country', 'name'=>'Страна', 'type'=>'do', 'options'=>'2', 'filter'=>true),
		array('id'=>'height', 'name'=>'Высота (мм)', 'type'=>'d'),
		array('id'=>'width', 'name'=>'Ширина (мм)', 'type'=>'d'),
		array('id'=>'length', 'name'=>'Длинна (мм)', 'type'=>'d'),
		array('id'=>'diametr', 'name'=>'Диаметр (мм)', 'type'=>'d'),
		array('id'=>'offset', 'name'=>'Вылет (мм)', 'type'=>'d'),
		array('id'=>'lamp_type', 'name'=>'Тип лампочки (основной)', 'type'=>'e',  'options'=>'E14|E27|G9|G4|R7S|GU10|GX5.3|GY6.35', 'need'=>true),
		array('id'=>'power', 'name'=>'Мощность лампы(Вт)', 'type'=>'d', 'need'=>true),
		array('id'=>'lamp_count', 'name'=>'Количество ламп', 'type'=>'d', 'need'=>true),
		array('id'=>'area', 'name'=>'Площадь освещения м2', 'type'=>'d'),
		array('id'=>'collection', 'name'=>'Коллекция', 'type'=>'s', 'filter'=>true),
		array('id'=>'style', 'name'=>'Стиль светильника', 'type'=>'do',  'options'=>'3'),
		array('id'=>'placing', 'name'=>'Способ размещения', 'type'=>'do',  'options'=>'4'),
		array('id'=>'material', 'name'=>'Материал', 'type'=>'dm',  'options'=>'5'),
		array('id'=>'color', 'name'=>'Цвет', 'type'=>'dm',  'options'=>'6'),
		array('id'=>'color_glass', 'name'=>'Цвет стекла', 'type'=>'dm',  'options'=>'7'),
		array('id'=>'lamps_exists', 'name'=>'Лампочки в комплекте', 'type'=>'c'),
		array('id'=>'price', 'name'=>'"Цена"', 'type'=>'d'),
	)),
);

$_order_statuses=array(0=>'Поставлен в очередь на обработку', 1=>'Ожидание поступления оплаты', 2=>'В процессе формирования', 3=>'Готов к выдаче', 999=>'Получен заказчиком');

$_cms_goods_admin_list_page_length=20;
?>